// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/logo.svg"
    | "/options.html"
    | "/popup.html"
    | "/profile/P1.png"
    | "/profile/P1.svg"
    | "/profile/P2.png"
    | "/profile/P2.svg"
    | "/profile/P3.png"
    | "/profile/P3.svg"
    | "/profile/P4.png"
    | "/profile/P4.svg"
    | "/profile/P5.png"
    | "/profile/P5.svg"
    | "/profile/P6.png"
    | "/profile/P6.svg"
    | "/profile/P7.png"
    | "/profile/P7.svg"
    | "/profile/P8.png"
    | "/profile/P8.svg"
    | "/profile/P9.png"
    | "/profile/P9.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
