
export enum MessageType {
    GET_PLUGIN_LIST = 'GET_PLUGIN_LIST',
    GET_PLUGIN = 'GET_PLUGIN',
    GET_PLUGIN_STATE = 'GET_PLUGIN_STATE',
    GET_PLUGIN_STATES = 'GET_PLUGIN_STATES',
    GET_PLUGIN_SETTINGS = 'GET_PLUGIN_SETTINGS',
    TOGGLE_PLUGIN = 'TOGGLE_PLUGIN',
    ENABLE_PLUGIN = 'ENABLE_PLUGIN',
    DISABLE_PLUGIN = 'DISABLE_PLUGIN',
    UPDATE_SETTING = 'UPDATE_SETTING',
    OPEN_MODAL = 'OPEN_MODAL',
    EXECUTE_PLUGIN = 'EXECUTE_PLUGIN',
    DOWNLOAD_IMAGE = 'DOWNLOAD_IMAGE',
    GET_FILE_SIZE = 'GET_FILE_SIZE',
    START_NETWORK_THROTTLE = 'START_NETWORK_THROTTLE',
    STOP_NETWORK_THROTTLE = 'STOP_NETWORK_THROTTLE',
}