
export enum MessageType {
    GET_PLUGIN_LIST = 'GET_PLUGIN_LIST',
    GET_PLUGIN_STATE = 'GET_PLUGIN_STATE',
    TOGGLE_PLUGIN = 'TOGGLE_PLUGIN',
    ENABLE_PLUGIN = 'ENABLE_PLUGIN',
    DISABLE_PLUGIN = 'DISABLE_PLUGIN',
    UPDATE_SETTING = 'UPDATE_SETTING',
    OPEN_MODAL = 'OPEN_MODAL',
    EXECUTE_PLUGIN = 'EXECUTE_PLUGIN'
}